# Generated by Django 5.2 on 2025-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
            ],
        ),
    ]
